# Generated by Django 2.2 on 2019-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('AC', 'Active'), ('FN', 'Finished')], default='CR', max_length=2),
        ),
    ]
