# Generated by Django 2.2 on 2019-04-30 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190429_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
            preserve_default=False,
        ),
    ]
