# Generated by Django 2.2 on 2019-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Active', 'Active'), ('Finished', 'Finished')], default='Created', max_length=20),
        ),
    ]
