# Generated by Django 2.2 on 2019-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_voter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
